import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Nav from '../components/Nav'
import FeatureBig from '../components/FeatureBig'
import CTA from '../components/CTA'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Subly - Subscriptions Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Hero />
      <FeatureBig
        id="features"
        heading="Manage your subscriptions"
        desc="Lorem ipsum dolo"
      />
      <FeatureBig
        heading="Get insights of your costs"
        desc="Lorem ipsum dolo"
        inverted
      />
      <FeatureBig
        heading="Never pay for an unwanted subscription again"
        desc="Get reminded before a subscription hits your card"
      />
      <CTA />
      <Footer />
    </div>
  )
}
