import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Nav from '../components/Nav'
import Footer from '../components/Footer'
import FeaturesList from '../components/FeaturesList'
import FeatureBig from '../components/FeatureBig'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <Hero />
      <FeatureBig />
      <FeatureBig />
      <FeaturesList />
      <Footer />
    </div>
  )
}
