name: Update Currencies
on:
  schedule:
    - cron: 0,10,20,30,40,50 * * * *
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Request
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://api.currencyapi.com/v3/latest?apikey=WTKRbe0vlotmLhKy4ijCpY5TW86TXGV9J42CT0LC
          save-name: currencies

      - name: Save Output File
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main # Pushes the updates to the main branch.
          folder: fetch-api-data-action # The location of the data.json file saved by the Fetch API Data action.
          target-folder: data # Saves the data into the 'data' directory on the main branch.
